


name: Cypress Tests Execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cypress run
      working-directory: ./CypressCloudDemo
      run:  |
        npm install
        npm run test
      continue-on-error: true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: CypressResults
        # A file, directory or wildcard pattern that describes what to upload
        path: "${{ github.workspace }}/cypress/reports"
